version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  dockerize:
    steps:
      - setup_remote_docker
      - run: docker build -f add/Dockerfile add:1.1

workflows:
    build-and-test:
      jobs:
        - build-and-test
    dockerize:
      jobs:
        - dockerize
